name 'u2fval'
maintainer 'Venkat Venkataraju'
maintainer_email 'venkat.venkataraju@gmail.com'
license 'MIT'
description 'Installs/Configures Yubico U2F Validation Server'
long_description 'Installs/Configures Yubico U2F Validation Server'
version '0.1.0'
